### ISSUE TITLE
"Invalid product license file No such file or directory" with Pythonnet

### ISSUE THREAD

**Issue by antodip** [dashingsoft/pyarmor#117]
Hi

I call encrypted algorithm from .net application using pythonnet framework and sometimes it gives "Invalid product license file No such file or directory". I can't figure out what it depends on, but often rebooting it solves the problem. Of course the plain text version always works.

All generated runtime files are in the same dir of obfuscated py file, i have tested it in several enviroments and the behaviour is always the same. 

I'm using Python 3.7.2 32 bit interpreter in Windows 10 64 bit.

Algorithms are encrypted using a registered pyarmor license with command line

	Pyarmor obfuscate --output  destdir   path\to\algorithm.py
	
I also tried to use command option  --restrict=0

Please help me.

**Comment by jondy** [comment]
Maybe pythonnet changes the current wok path, so that pyarmor could not find the license file. 

Try to insert some debug code in the runtime file `pytransform.py`  which is generated in the output path.  
First obfuscate the scripts with `--no-cross-protection`
```
pyarmor obfuscate --no-cross-protection --output  destdir   path\to\algorithm.py
```
Then edit the file `destdir/pytransform.py`,  add these lines in the end of function `_load_library`
```
    print("current path is %s" % os.path.abspath('.'))
    print("Search path is %s" % os.path.abspath(path))
```

Then check whether `license.lic` of the obfuscated scripts in the search path.

**Comment by jondy** [comment]
Besides, check the property `--file__` of `pytransform.py` in the pythonnet environment. If it's not set correctly, pyarmor also couldn't find the license file. In this case try to set `--runtime-path` as obfuscating the scripts.

**Comment by antodip** [comment]
Thank you for the prompt reply.

I have tried everything but unfortunately:

1) the paths are correct, 
2) __file__ is correctly set 
3) Also building with --runtime--path it doesn't work.

Output:

__file__:  c:\pyc\a\pytransform.py
current path is D:\Projects\PDPro\trunk\Main\bin\Release
Search path is c:\pyc\a
Invalid input packet.
Check license failed

Pythonnet is a .net framework that simply provide an integration of the C Python engine with the .NET runtime. It uses the python interpreter installed on the machine.

**Comment by jondy** [comment]
Is there any 'pytransform.key' or 'license.lic' in the path D:\Projects\PDPro\trunk\Main\bin\ReleaseIf there is, remove them. pyarmor will read license file in the current path at first.-------- Original Message --------Subject: Re: [dashingsoft/pyarmor] "Invalid product license file No such file or directory" with Pythonnet (#117)From: antodip To: dashingsoft/pyarmor CC: Jondy ,Comment Thank you for the prompt reply.
I have tried everything but unfortunately:

the paths are correct,
file is correctly set
Also building with --runtime--path it doesn't work.

Output:
file:  c:\pyc\a\pytransform.py
current path is D:\Projects\PDPro\trunk\Main\bin\Release
Search path is c:\pyc\a
Invalid input packet.
Check license failed
Pythonnet is a .net framework that simply provide an integration of the C Python engine with the .NET runtime. It uses the python interpreter installed on the machine.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dashingsoft/pyarmor/issues/117?email_source=notifications\u0026email_token=AA35AM44UHPNANL2LJDWWCDQKN55BA5CNFSM4IYI65PKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7DPUCA#issuecomment-533133832",
"url": "https://github.com/dashingsoft/pyarmor/issues/117?email_source=notifications\u0026email_token=AA35AM44UHPNANL2LJDWWCDQKN55BA5CNFSM4IYI65PKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7DPUCA#issuecomment-533133832",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by antodip** [comment]
Unfortunately there are no runtime files there

**Comment by jondy** [comment]
>I'm using Python 3.7.2 32 bit interpreter in Windows 10 64 bit.
Why do you use 32 bit Python in 64 bit Windows? pyarmor may not work. How about use 64 bit Python?

**Comment by antodip** [comment]
Unfortunately due to several technical reasons we are forced to compile our application to 32 bit and the 32-bit version of pythonnet requires the 32-bit python interpreter

**Comment by jondy** [comment]
In this case, try to use `--platform win32` to obfuscate the scripts, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-scripts-to-other-platform

**Comment by antodip** [comment]
even using 32-bit  platform the behavoiur is always the same

**Comment by jondy** [comment]
:( i'm out Of office now. i'll be back next Monday and track this issue.

**Comment by jondy** [comment]
There are somethings need to be clear

1. Does pyarmor work with 32-bit python in 64-bit windows if without pythonnet? For example,
```
pyarmor obuscate foo.py
cd dist/
python foo.py
```

2. What's the exact error message?
In the beginning, it raises error `No such file or directory`, but in the next session, it raises error "Invalid input packet.
Check license failed"
Does the first error message appear afterwards?

The reason of these 2 errors are totally different.

**Comment by antodip** [comment]
1) Yes, if I run the script with the python interpreter it works.

2) I see only the message 

"Invalid input packet.
Check license failed"

and systemExit: 1

**Comment by jondy** [comment]
Try to use the prebuilt library built by vs2015 as the following way:
```
pyarmor download vs2015/x86
pyarmor obfuscate --platform vs2015/x86 foo.py
cd dist/
python foo.py
```
To be sure it works out of pythonnet, then copy all the files in the `dist/` into the Pythonnet environment, and try to `import foo` .

**Comment by antodip** [comment]
Ok, now it seems to work. :)
