### ISSUE TITLE
License Key removal caused failures.

### ISSUE THREAD

**Issue by tejaschandra84** [dashingsoft/pyarmor#122]
We have purchased a license key for obfuscating the code and after the recent changes to the code. All our builds are failing due to the `pyarmor register <code>` not working anymore. We require the file now while obfuscating the code. We would appreciate a mechanism for the existing customers to use the existing key else, please elucidate a mode through which, we can get the key file from you.

**Comment by jondy** [comment]
Just edit the file "license.lic" in the pyarmor installed path, then  replace the content with your purchased code. 

In PyArmor 5.6, command "register" is changed to register keyfile.

Besides, backup the global capsule in the home path which named ".pyarmor_capsule.zip".

**Comment by jondy** [comment]
If PyArmor has been upgraded, it need do nothing. The license file of PyArmor will not be overwritten by pip upgrade command. `pyarmor obfuscate` should still work.

In order to the previous obfuscated scripts could work, you need use the same capsule ".pyarmor_capsule.zip" which in the user HOME path to obufscate scripts.  It's recommanded to backup this file `~/.pyarmor_capsule.zip`.

If you prefer use new keyfile, please forward the registration email received from share*it or regnow, I'll send you the keyfile to original registration email. But all the previous obfuscated scripts need to be obfuscated again, and all the "license.lic" issued for the obfuscated scripts need to be generated by new capsule either.
