### ISSUE TITLE
RuntimeError: Check restrict mode failed in setup.py with pyarmor 5.6.4 on py3.6 win64

### ISSUE THREAD

**Issue by masariello** [dashingsoft/pyarmor#128]
I'm using this [setup.py.txt](https://github.com/dashingsoft/pyarmor/files/3767852/setup.py.txt) to obfuscate the lib directory created by setuptools

I'm getting the 'RuntimeError: Check restrict mode failed' error no matter what I do.

**Comment by jondy** [comment]
Replace line 26 in `setup.py` with
```
check_call([pyarmor, 'obfuscate', '-O', obfuscated_mod_dir, '--recursive', '--restrict', '0'] + py_files)
```
For more information about restrict mode, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#improving-the-security-by-restrict-mode

**Comment by masariello** [comment]
Thanks. That worked.

**Comment by YuNats** [comment]
For someone who in same trouble, 
It might caused by different version of python.
Thus I set python versionsame as obfuscated environment  to run the obfuscated file .

Below is my case:
1. Run "pyarmor obfuscate app.py" in vertiual env (venv) of python3.9.9.
2. Make venv in other directory . (python3.10 was selected automatically with my computer setting)
3. Copy and paste the "dist" to other directory where created venv (python 3.10).
4. activate venv and run dist\app.py.  But it didn't work with same error message.
