### ISSUE TITLE
RuntimeError: Verify license failed

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#145]
Hi @jondy ,

I purchased a license, i generated some user licenses, copied the license.lic to the pytransform , works locally fine... however, on the remote machine it's constantly getting 

```
RuntimeError: Verify license failed
```

local system was debian, remote system is ubuntu 18.04

Can you help?

**Comment by VeNoMouS** [comment]
Debian using py3.7, ubuntu was 3.6

however , using 3rd party repo, to 3.7 for ubuntu, it now works...


i was getting 

```
SystemError: unknown opcode
```

With a direct copy of my debian pytransform, if i copied dist/pytransform from ```pyarmor runtime``` and replaced the license.lic, i was getting `Verify license failed`

in future, how can i avoid this?

**Comment by jondy** [comment]
Thank you for purchasing pyarmor license.

The major/minor  version of Python in build machine should be same as in target machine. Because the scripts will be compiled to byte-code before they’re obfuscated, so the obfuscated scripts can’t be run by all the Python versions as the original scripts could. 

Refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts

One solution is to install Py3.6 in build machine,  refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-by-other-version-of-python

**Comment by VeNoMouS** [comment]
Ah got you, so basically its the same a pyc ... 

I understand now

I did try read all the doco before, but it wasn't 100% clear, doco is good, but i think it could do with some work, I've personally never used pyarmor before, so the learning curve was quite a bit and the doco is explained in such a way that you need pyarmor experince , so as a new comer, it made no sense...

like... i didnt know how to check the details of the license.lic i found out that you can only check it from inside the code your obfuscating.. seemed silly...

bunch of small things that just arent documated very well

thanks heaps for your fast response @jondy
