### ISSUE TITLE
Workflow concern for Group License

### ISSUE THREAD

**Issue by GODIC715** [dashingsoft/pyarmor#1455]
Hi, 

We've bought the group license, and we've some concern regarding activating it.

We've checked the documentation and we couldn't find an answer. 

We are working with an EC2 instance on AWS (Host) and have a github actions workflow that uses this instance to download a special docker image with our dependencies and runs our build scripts using the container which was created from that image.

The EC2 host will be used to activate pyarmor using the email you sent us, then we'll create an image of it after it's activated.

So our workflow is as follows

Github actions -> uses our AWS EC2 instance (pyarmor host) -> Create pyarmor license file -> download docker image and create docker container -> run our build scripts -> run pyarmor using  license file created from EC2 machine (host)

We'd like to know if the group license supports this type of workflow or not.

Thank you.

**Comment by jondy** [comment]
Check AWS EC2 instance by this way
1. Install Pyarmor 8.3.5+
2. Print machine id of AWS EC2 instance:
```
python -c"from pyarmor.cli.core.pytransform3 import get_hd_info
print(get_hd_info(20))
```

Restart AWS EC2 instance, and print machine id again

If machine id is same after reboot, it works.

Otherwise, I don't know if there is any extra options to request AWS EC2 instance so that node name, mac address and serial number of virtual hard disk keep same.

If could not get same machine id of AWS EC2 instance by any way, this workflow doesn't work.

**Comment by hadywalied** [comment]
hey @jondy 
I tried your code on 2 different configurations (instance types) and got this result

t2.medium -> b'k2a942195a0b2c0ba5d287ed7c1ddd3ea'

t2.micro -> b'k2a942195a0b2c0ba5d287ed7c1ddd3ea'

does that mean that the workflow works ?

**Comment by jondy** [comment]
@hadywalied

yes, it should be OK.
