### ISSUE TITLE
execution of packed elf file returns different error on centos6,7

### ISSUE THREAD

**Issue by newbieh4cker** [dashingsoft/pyarmor#148]
I've packed my python file into one binary(elf) with "ubuntu 16.04, gcc7.4.0, glibc 2.27"
When executing pacekd file....

CentOS7( gcc 7.3.1, glibc 2.17) returns below error
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/_MEImmF6JY/libstdc++.so.6)

CentOS6( gcc 7.3.1, glibc 2.12) returns below error
Load /tmp/_MEIkd39JA/_pytransform.so failed:
Failed to load dynlib/dll '/tmp/_MEIkd39JA/_pytransform.so'. Most probably this dynlib/dll was not found when the application was frozen.

However for the "_pytransform.so", I did insert them to a 'spec file' when I packed.
here is part of my spec file
('/home/test/pyarmor_test/dist/obf/dist/_pytransform.*', '.'),

any ideas??

**Comment by jondy** [comment]
For CentOS7,  do you add file `libstdc++.so.6` to `.spec` file? If you have built some `.so` files, try to link `libstdc++` with option `-static-libstdc++`, it seems in the build machine glibc is 2.18. So the solution is, do not pack the `libstdc++.so.6` from build machine, use the one in target machine. 

For CenOS6 which glibc is 2.12, there is a known issue, because `_pytransform.so` need glibc 2.14 or higher, one solution is to patch `_pytransform.so`, refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#lib64-libc-so-6-version-glibc-2-14-not-found

**Comment by newbieh4cker** [comment]
hello, sorry for late reply.
i did patched _pytransform.so.

original _pytransform.so
![image](https://user-images.githubusercontent.com/23703741/69506694-179c5b00-0f73-11ea-991b-1cc9b90f0c06.png)

patched _pytransform.so
![image](https://user-images.githubusercontent.com/23703741/69506710-23881d00-0f73-11ea-88eb-5940d7cd57a0.png)

Using patched so file for pack, and when executing..
CentOS7 return
- ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/_MEIWJRUhR/libstdc++.so.6)

CentOS6 return
 - ImportError: /lib64/libc.so.6: version `GLIBC_2.13' not found (required by /tmp/_MEIjt6U6k/psutil/_psutil_linux.cpython-35m-x86_64-linux-gnu.so)

**Comment by jondy** [comment]
The problem is that your scripts import binary module `psutil`, however the module file `_psutil_linux.cpython-35m-x86_64-linux-gnu.so` is built with glibc 2.18 in your build machine as you run `pip install psutil` in the build machine.

The solution is, run `pip install psutil` in the CentOS6, then find the file `_psutil_linux.cpython-35m-x86_64-linux-gnu.so`, and copy it to build machine. After that you may uninstall psutil in the CentOS6.

In build machine, pack this copied `_psutil_linux.cpython-35m-x86_64-linux-gnu.so` by `--add-binary` to override the one found by pyinstaller automatically.

It's better to check all the other `.so` files which are packed into one binary file. You can first pack your scripts into one folder other than one file, there are all the required `.so` files in the output folder.  Check the version information by `readelf -V xxxx.so`, if there is glibc > 2.12 dependency, this `.so` file also need to be built in the CentOS 6.

**Comment by newbieh4cker** [comment]
Okay, I modified my spec file  to include psutil so file from centos6 while packing.

binaries = [
  ('./_psutil_linux.cpython-35m-x86_64-linux-gnu.so', '.'),
]
a = Analysis(['asd.py'],
             pathex=['/home/xxx/xxx/xxx/pyarmor'],
             binaries=binaries,
             ~~~~~

and still no lucks... T.T

**Comment by jondy** [comment]
Remove `-F` or `--onefile` from your `.spec` file, pack the scripts by pyinstaller directly, for example,
```
pyinstaller --clean asd.spec
```
Search the file `_psutil_linux.cpython-35m-x86_64-linux-gnu.so` in the dist folder, make sure 
* There is only one in the dist folder
* It's same as the one copied from centos6
* The final binary file could run in the build machine

**Comment by newbieh4cker** [comment]
Is "/lib64/libc.so.6: version `GLIBC_2.14' not found" error occurs if other so file (not _pytransform.so) has dependecy with glib2.12??

Below is the screenshot from CentOS7 ( it's build machine )
![image](https://user-images.githubusercontent.com/23703741/69527960-b2fff100-0fb0-11ea-8c7b-333d5b72b783.png)

As you can see, I'm using local _pytransform.so file for pack, that has been patched.
Running ELF binary on CentOS7 works fine, but in CentOS6 glibc_2.14 not found occurs again,.

**Comment by jondy** [comment]
>Is "/lib64/libc.so.6: version `GLIBC_2.14' not found" error occurs if other so file (not _pytransform.so) has dependecy with glib2.12??

>Below is the screenshot from CentOS7 ( it's build machine )

>As you can see, I'm using local _pytransform.so file for pack, that has been patched.
>Running ELF binary on CentOS7 works fine, but in CentOS6 glibc_2.14 not found occurs again,.

To fix CentOS6 issue, please upgrade pyarmor to latest version v5.7.8, it's released several hours ago and support centos6 platform (glibc < 2.14).

Then pack your scripts with extra obfuscating options `--platform centos6.x86_64`, for example,
```
pyarmor pack -x " --platform centos6.x86_64" ...other options... foo.py
```

By this way, the patched `_pytransform.so` will be packed into the final bianry.

And you need not patch `_pytransform.so` in build machine by yourself.

**Comment by jondy** [comment]
Only `_pytransform.so` is generated by pyarmor, I'm not sure the other `.so` files, which are dependencies of your scripts.

**Comment by newbieh4cker** [comment]
Okay, after upgrading pyarmor with pip.
`pyarmor` itself just doesn't work in CentOS6 (docker image)

![image](https://user-images.githubusercontent.com/23703741/69594447-b55d5c00-103f-11ea-98d6-e6d1d2db59c3.png)

**Comment by jondy** [comment]
What's the output of this script in CentOS6:
```
import platform
print(platform.system().lower())
print(platform.libc_ver())
```

**Comment by newbieh4cker** [comment]
in CentOS 6.10
![image](https://user-images.githubusercontent.com/23703741/69598253-13903c00-104c-11ea-8d38-1eddfb2158c2.png)

**Comment by jondy** [comment]
There is a bug to check libc version, a quick workaround is editting `/usr/lib/python3.5/site-packages/pyarmor/pytransform.py` at line 199, replace `len(v) == 2` with `len(v) >=2`:
```
            if len(v) >= 2 and (int(v[0]) * 100 + int(v[1])) < 214:
```

**Comment by jondy** [comment]
Sorry, I miss this patch in v5.7.8, a quick workaround is editting /usr/lib/python3.5/site-packages/pyarmor/pytransform.py at line 197, add these lines:
```
        elif cname == 'glibc' and cver.find('.') > 0:
            v = cver.split('.')
            if len(v) >= 2 and (int(v[0]) * 100 + int(v[1])) < 214:
                plat = 'centos6'
```
