### ISSUE TITLE
[BUG] mitmdump not working for obfuscated script

### ISSUE THREAD

**Issue by mrkvn** [dashingsoft/pyarmor#1906]
Prerequisite:
`pip install mitmproxy`

This python script works with command `mitmdump -s main.py`. Prints both `from response` and `from outside response`

```py
# main.py
def response(flow):
    print("from response")
print("from outside response")
```

When obfuscated using `pyarmor gen main.py`, only prints `from outside response`.

Tried for both MacOS and Windows.

**Comment by jondy** [comment]
I have no idea about `mitmdump`, please check
https://pyarmor.readthedocs.io/en/latest/how-to/third-party.html

Also check
https://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html#the-differences-of-obfuscated-scripts

Because it seems `mitmdump` will parse the Python script and execute it, I'm not sure it would work with the obfuscated scripts.
