### ISSUE TITLE
[BUG] Memory Leak in Pyarmor 9.0.5 when performing complex bytes slicing

### ISSUE THREAD

**Issue by Apprisco** [dashingsoft/pyarmor#1985]
`return [data[address-lower_bound:(address-lower_bound)+size] for address in addrs]`
The above type of list slicing seems to cause a memory leak when using BCC/RFT mode with PyArmor 9.0.5.

**Comment by Apprisco** [comment]
Seems like when the above list is created, it is not removed.

**Comment by jondy** [comment]
I'll appreciated if you could provide the reproduced steps, which options is used, which python version, which platform.

**Comment by Apprisco** [comment]
That's not a reason to close the issue @jondy
python 3.11 python 3.12 python 3.13 Windows 11 Pro 
BCC options used

Again, just slice a bytes string in a list and observe it never getting GCed

**Comment by jondy** [comment]
This issue is easy to reproduce in your enviroments, but for me, I may need lot of time to reproduce if no command options, no python version and no platform.

I may spent half an hour test it in Darwn, it's fine, then test it in Linux, it's fine. Then windows. I need one hour to find it.

So why could you provide one simple script and full command line to reproduce it?

I think it will not spent too many time for you.

That's why I close this issue.

**Comment by jondy** [comment]
Anyway, I'll do a test like this

```python
# foo.py

def main():
   data = b'1234567890'
   addrs = 3, 5
   size = 2
   lower_bound = 0
   return [data[address-lower_bound:(address-lower_bound)+size] for
  address in addrs]

print(main())
```

Reproduced steps:
```bash
pyarmor gen --enable-bcc foo.py
python dist/foo.py
```
