### ISSUE TITLE
Pack with Niutka

### ISSUE THREAD

**Issue by BlackRouter** [dashingsoft/pyarmor#209]
hi
can i use nuitka + pyarmor for more Security??

i think nuitka is better from pyinstaller...

**Comment by jondy** [comment]
I'll research Nuitka to check the possibilities.

**Comment by jondy** [comment]
Because the obfuscated scripts could be taken as normal scripts with an extra runtime package `pytransform`, they also could be translated to C program by Nuitka. When obfuscating the scprits, the option ``--restrict 0`` and ``--disable-cross-protection`` should be set, otherwise the final C program could not work. For example, first obfustate the scripts
```
    pyarmor obfuscate --restrict 0 --disable-cross-protection foo.py
```
Then translate the obfuscated one as normal python scripts by Nuitka
```
    cd ./dist
    python -m nuitka --include-package pytransform foo.py
    ./foo.bin
```
There is one problem is that the imported modules (packages) in the obfuscated scripts could not be seen by Nuitka. To fix this problem, first generate the corresponding ``.pyi`` with original script, then copy it within the obfuscated one. For example::
```
    # Generating "mymodule.pyi"
    python -m nuitka --module mymodule.py

    pyarmor obfuscate --restrict 0 --no-bootstrap mymodule.py
    cp mymodule.pyi dist/

    cd dist/
    python -m nuitka --module mymodule.py
```

But it may not take advantage of Nuitak features by this way, because most of byte codes aren't translated to c code indeed.

**Comment by BlackRouter** [comment]
> --disable-cross-protection

thank you jondy , but `--disable-cross-protection` not work in windows platform.

**Comment by jondy** [comment]
Sorry, it should be `--no-cross-protection` in the latest version.

**Comment by BlackRouter** [comment]
thank you work it
