### ISSUE TITLE
[Query] Sub Licenses for a project.

### ISSUE THREAD

**Issue by e0lithic** [dashingsoft/pyarmor#222]
Hello again. 

### Project Structure

|--------> entry_script.py
|--------> feature1_dir (package)
|--------> feature2_dir (package)

### Usecase
- Entry script imports functions classes from the various feature packages.
- Feature1 is supposed to have Expiry date 1 
- Feature2 is supposed to have Expiry date 2
- Entry script would be imported by the customer as library for use. However feature1 and feature2 can be totally abstracted with highest level restrict modes.

In such a case, would you recommend  obfuscating the feature directories independently with their independent licenses in the form of packages . Or there could be project or child project based approaches which would help in maintenance and incremental builds.

Thanks

**Comment by jondy** [comment]
Because only one `license.lic` of the obfuscated scripts can take effect at the same time in one Python interpreter, each features must be obfuscated with `--enable-suffix` to create unique runtime package.  Refer to [Solve Conflicts With Other Obfuscated Libraries](https://pyarmor.readthedocs.io/en/latest/advanced.html#solve-conflicts-with-other-obfuscated-libraries), it means that you need purchase many PyArmor's licenses if there are many features.

In this case, I think it's better to use a plugin script to control the permission of each feature. The plugin script is a separated script, it will be injected into the entry script only when the script is obfuscated. Refer to [Using Plugin to Extend License Type](https://pyarmor.readthedocs.io/en/latest/advanced.html#using-plugin-to-extend-license-type)

**Comment by e0lithic** [comment]
Thanks, for the detailed explanation. Closing the issue for now.
