### ISSUE TITLE
Pyarmor works for Python 3?

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [dashingsoft/pyarmor#366]
Can Pyarmor work with Python3? I mean if I am having Python3 Installed and I install Pyarmor in Python3 and try to pack a script which is made with Python3, Will it work?

**Comment by jondy** [comment]
It doesn't work if the minor version is different. For example, obfuscated by Python3.5, then run it by Python3.7.

**Comment by Vedant-Bhalgama** [comment]
What is the reason behind this ?

So I will have to install both python3.5 and 3.7?

**Comment by jondy** [comment]
Because pyarmor first compiles `.py` to byte code, then obfuscates byte code. The byte code isn't compatible in different Python versions.

And you have to install many python versions. Refer to [Obfuscating Scripts By Other Python Version](https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-by-other-python-version)
