### ISSUE TITLE
How to debug it that encrypted script

### ISSUE THREAD

**Issue by yq1320** [dashingsoft/pyarmor#382]
When I want to do breakpoint debugging of an encryption script, how do I do it?

**Comment by jondy** [comment]
It's disallowed to debug an encrypted script.

**Comment by yq1320** [comment]
Pyarmor对py程序加密后不能进行调试，您这边有替代方案可以对加密后的代码进行调试吗？

**Comment by ChaochCN** [comment]
I suggest that you add output log to suspicious breakpoints, drag your exe or py to the command line window to execute, so that you can get more detailed report information.
我建议你，对可疑的断点都加上输出日志，把你的exe或py拖拽到命令行窗口中执行，这样可以获得更完善的报告信息。

**Comment by yq1320** [comment]
Thinks for your idea，I'll try to do it.

**Comment by yq1320** [comment]
But I hope your business plan has a better solution。

**Comment by jondy** [comment]
允许调试就要让调试器得到代码对象（ code object）的所有属性，这等价于调试器可以得到加密代码对应的 .pyc 文件，所以调试功能和加密功能是冲突的。

PyArmor 基本不影响原来的脚本，所以一般的建议方案是调试好脚本之后然后在加密。

对于生产环境的加密脚本，最好还是设计好日志，增加必要的 `logging.debug`，当出现问题的时候，打开调试开关，通过调试日志信息来解决处理生产环境的问题。

**Comment by ChaochCN** [comment]
I've always been curious about how the bot layer of pyarmor is implemented.
The best way of a python encrypt tool, that  I can conceive is asymmetric encryption and custom Python interpreter.
In my opinion it must be  ingenious design.
we should not be suprise about that pyarmor disallows anyone debug an encrypted script(even author self), otherwise pyarmor is a joke(or we all fools).

**Comment by yq1320** [comment]
I know that the Py file after The Encryption to Pyarmor is not allowed to be debugged, and it may have its own meaning.

**Comment by yq1320** [comment]
Thank you very much for your answer.
