### ISSUE TITLE
OSError: could not get source code

### ISSUE THREAD

**Issue by sobassy** [dashingsoft/pyarmor#389]
I tried obfuscate scrapy projects.

in scrapy==1.8.0, I could obfuscate this, and exited gracefully.
but in scrapy==2.2.0,  I could obfuscate this, and caused this Error: OSError: could not get source code
so, I thought the solution is side of pyarmor.

I checked inspect.py, and debug;

in inspect.py line 786;
```
# raise OSError('could not get source code')
raise OSError('could not get source code', file)
```

output is 

```
OSError: [Errno could not get source code] <frozen spiders.dior>
```

so I thought When read obfuscated file recursively, cannot load frozen object.

If you have any advices, please give me any solutions. thank you

**Comment by jondy** [comment]
Why do you think the solution is side of pyarmor, :). Instead, the problem is in side of `scrapy 2.2.0`.

After the scripts is obfuscated by pyarmor, the source code could not be got by any way. As you have found, `inspect.py` raises exception because it tries to read the source code from obfuscated scripts. 

I guess `scrapy 1.8.0` doesn't try to get source code by `inspect.py`, so it works.

**Comment by sobassy** [comment]
dear jondy,

Thank you for your advice. I will check release notes in scrapy. 
I'm sorry to take the trouble ;)

thank you
