### ISSUE TITLE
_pytransform can not be loaded twice

### ISSUE THREAD

**Issue by ukab23** [dashingsoft/pyarmor#52]
When does anyone get this message '_pytransform can not be loaded twice'. How can I remove this?

**Comment by jondy** [comment]
Here it's the reason
https://pyarmor.readthedocs.io/en/latest/questions.html#pytransform-can-not-be-loaded-twice

To remove this, hack `pytransform.py` in the PyArmor installed path, comment this 2 lines in the function `pyarmor_runtime`
```
        if _pytransform is not None:
            raise PytransformError('_pytransform can not be loaded twice')
```
But it will reduce the security of obfuscated scripts.

**Comment by PidgeyBE** [comment]
If this reduces security of obfuscated scripts, it's not really security, because anyone can edit the pytransform.py file, right?

**Comment by jondy** [comment]
The security here means the security of `_pytransform.so`. In order to protect `_pytransform.so`, PyArmor will insert some extra code as obfuscating the scripts, refer to

https://pyarmor.readthedocs.io/en/latest/how-to-do.html#special-handling-of-entry-script

When the obfuscated script is running, it will check `pytransform.py` and `_pytransform.so` to be sure they're not changed any more. If `_pytransform.so` could be loaded more than once, maybe the file of `_pytransform.so` checked by protection code isn't the real dynamic library used by obfuscated scripts.

This limitation may be removed later if there is another better way to protect `_pytransform.so`
