### ISSUE TITLE
Getting error (NameError: name '__pyarmor__') while run celery task

### ISSUE THREAD

**Issue by pardeepbeniwal** [dashingsoft/pyarmor#551]
Hi,

I have obfuscated my django project. Runserver command is working fine but celery run command giving error: _**NameError: name '__pyarmor__' is not defined**_.

celery run command: ```celery worker --app=app_name-l info```

Please help @jondy

**Comment by jondy** [comment]
Please first read this page
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html

And find the solution here
https://pyarmor.readthedocs.io/en/latest/questions.html

If you use purchased version, I suggest obfuscating the scripts by suer mode.

**Comment by pardeepbeniwal** [comment]
@jondy I think you are talking about **Super mode** not _suer mode_. But we can't use super mode because we are using python3.5. If you have time.. can you share steps for django and celery run command ?

**Comment by jondy** [comment]
Sorry, I don't support this. This issue is related to the usage of pyarmor, not bug
https://pyarmor.readthedocs.io/en/latest/license.html#technical-support

The problem is that there is no bootstrap code are executed when starting celery task
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

And here it's an example of Django
https://pyarmor.readthedocs.io/en/latest/examples.html#running-obfuscated-django-site-with-apache-and-mod-wsgi
