### ISSUE TITLE
Marshal loads failed when running xxx.py

### ISSUE THREAD

**Issue by xennygrimmato** [dashingsoft/pyarmor#57]
I am running pyarmor 4.4.3 and getting this Pytransform Error: ` Marshal loads failed when running <filename>.py`.

I followed the steps mentioned here - [https://pyarmor.readthedocs.io/en/v5.2.1/questions.html#marshal-loads-failed-when-running-xxx-py](https://pyarmor.readthedocs.io/en/v5.2.1/questions.html#marshal-loads-failed-when-running-xxx-py) - but it seems that I have done everything correctly so far.

Is there a way I can run pyarmor in debug mode, capture some internal logs to see what's wrong exactly?

**Comment by jondy** [comment]
Run the obfuscated script with `-d`, it will show more information
`python -d obfuscated_foo.py`

**Comment by xennygrimmato** [comment]
When I do that, pytransform does not get loaded, I'm not sure why.
I see this error: `pytransform.PytransformError: ('Could not load _pytransform from "%s"', '<insert_current_dir_path>')`

The `_pytransform.so ` file is in the same directory as the obfuscated file that I'm trying to run.

**Comment by jondy** [comment]
Hi, the latest PyArmor is  v5.2.3, there are lot of changes from v4.4.3.  How about try the latest version?

**Comment by xennygrimmato** [comment]
Hi @jondy , I tried using v5.2.3.  `pyarmor init` works fine, but `pyarmor build` throws an error, not providing details about the error.

```
INFO     Create configure file ...
INFO     Configure file <local_path>/.pyarmor_config created
INFO     Create pyarmor command ...
INFO     PyArmor command <local_path>/pyarmor created
INFO     Project init successfully.
ERROR 
```

I am currently using this example - [https://github.com/dashingsoft/pyarmor/blob/master/src/examples/build-with-project.sh](https://github.com/dashingsoft/pyarmor/blob/master/src/examples/build-with-project.sh) - to obfuscate my application. Everything had been working fine so far with version 4.4.3, but obfuscation started failing a couple of days back. I am planning to buy a license, any help here would be really appreciated.

**Comment by jondy** [comment]
There are some changes for Project since v4.4.3, refer to

https://github.com/dashingsoft/pyarmor/releases/tag/v5.2.0

I'll check the example script later to be sure it works in v5.2.3

Now, just build project with PYTHONDEBUG=1 to get the trace back of exception
```
cd <local_path>
PYTHONDEBUG=y ./pyarmor build -b
```

**Comment by xennygrimmato** [comment]
Thank you.
This assertion is failing - [https://github.com/dashingsoft/pyarmor/blob/e2690244a2fb8f573d3154e3e036e6c353a4979d/src/project.py#L100](https://github.com/dashingsoft/pyarmor/blob/e2690244a2fb8f573d3154e3e036e6c353a4979d/src/project.py#L100) is failing.

**Comment by jondy** [comment]
I got it.  Since v5.2.0, the capsule of project uses global capsule by default. 

 First to be sure global capsule exists, which is `~/.pyarmor_capsule.zip`, if not, create it by
`cd ~; pyarmor capsule`

 See which capsule is used in this project
`cd <local path>; ./pyarmor info`

To be sure the capsule of this project exists, or update the capsule of this project
`cd <local path>; ./pyarmor update --capsule=~/.pyarmor_capsule.zip`

**Comment by xennygrimmato** [comment]
Is `update` a valid option?

```
usage: pyarmor [-h] [-v] [-q] <command> ...
pyarmor: error: argument <command>: invalid choice: 'update' (choose from 'capsule', 'obfuscate', 'init', 'config', 'info', 'check', 'build', 'licenses', 'hdinfo', 'benchmark', 'pack')
```

**Comment by jondy** [comment]
Sorry, it should be `config`,  `pyarmor config --capsule=~/.pyarmor_capsule.zip`

**Comment by xennygrimmato** [comment]
Thank you for the help, this worked. I'll create a PR today to update the script to obfuscate an app.

**Comment by boechat107** [comment]
I'm getting the same error, but probably because of a different reason.

I'm obfuscating my scripts while building a multi-stage Docker image and everything works perfectly when building the image locally. However, images built by a CI using exactly the same Dockerfile are not working, printing the same error reported in this issue. I tried removing any cache layer and base image to replicate the error locally, but I couldn't get it. Locally the image works as expected.

@jondy, do you have a guess?

I'm using Pyarmor 5.5.6 and a private code that I recently bought.

Thanks for any help!

**Comment by jondy** [comment]
@boechat107 
First to be sure the python version used by CI is same as the python version used to obfuscate the scripts.  
Then check if there is any other 'license.lic` or `pytransform.key` in the current work path of CI.  It should only one "pytransform.key" and "license.lic" with the obfuscated scripts.
If both of them are OK, try to obfuscate a simple script, and run it in CI.

**Comment by boechat107** [comment]
I think I probably didn't make myself clear. All the obfuscation steps are executed by Docker while *building* the image, I don't use anything else from the host. For both scenarios, local and remote building, I don't have any of the mentioned files and the Python versions are the same (since they share the same base image).

The following lines are just a single stage of the complete Dockerfile, but they show how I'm obfuscating the project scripts:

```dockerfile
FROM base-deploy-image AS pyarmor-image

ARG PYARMOR_PRIVATE_CODE
ARG PYARMOR_EXPIRATION_DATE

ADD ./project_dir /app/project_dir
RUN pyarmor register $PYARMOR_PRIVATE_CODE && \
    pyarmor obfuscate --recursive \
        --output dist/project_dir project_dir/main.py && \
    rm dist/project_dir/license.lic && \
    pyarmor licenses \
        --expired $PYARMOR_EXPIRATION_DATE $PYARMOR_PRIVATE_CODE && \
    cp licenses/*/license.lic dist/project_dir/
```

@jondy, thanks for your quick answer.

**Comment by jondy** [comment]
@boechat107 does the default `license.lic` work? Do not remove the default license, try it works or not.

If it works, try to use some short code other than `$PYARMOR_PRIVATE_CODE` to generate expired license, for example,
```
pyarmor licenses --expired $PYARMOR_EXPIRATION_DATE mydocker-0002 && \
cp licenses/mydocker-0002/license.lic dist/project_dir
```
