### ISSUE TITLE
Warning: code object xxxx isn't wrapped

### ISSUE THREAD

**Issue by lhmwzy** [dashingsoft/pyarmor#59]
INFO     Obfuscate scripts in path "D:\lhmrpa\f44\f44\codes"
INFO     Use cached capsule C:\Users\gx\.pyarmor_capsule.zip
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
INFO            Main.py -> dist\Main.py
INFO            GlobalFun.py -> dist\GlobalFun.py
Warning: code object runf_44 isn't wrapped
INFO     2 scripts have been obfuscated
INFO     Make runtime files
INFO     Insert bootstrap code to entry script dist\main.py
INFO     Obfuscate 2 scripts OK.

这种警告是什么原因引起的？可以忽略吗？

**Comment by jondy** [comment]
这是因为个别函数中包含特殊情况的跳转指令而引起的，可以忽略，只是个别的函数没有进行加密处理。
例如，如果这个函数编译成为 byte code 之后如果有类似这样的一条指令
···
JMP 126
···
在加密之前，这条指令占用两个字节。而在加密之后，因为在函数头部插入了额外的指令，这个跳转指令就变成了
```
JMP 138
```
在 Python3.6之后，这条指令需要4个字节，遇到这种情况，目前 PyArmor 就不会加密这个函数， 并显示这个警告信息。

如果想要避免这个问题，可以尝试在函数里面增加一些冗余的语句，让跳转长度不要在临界值即可。

后面的版本会考虑解决这个问题，因为一旦修改原来的指令长度，代码块所有的相对跳转、绝对跳转指令都需要调整，情况比较复杂，所以遇到这种情况，暂时忽略了。

**Comment by lhmwzy** [comment]
不加密的意思是可以通过.pyc文件反编译得到源码吗？

**Comment by jondy** [comment]
不可以的，只是这一个函数的 codeobject 没有加密，整个模块还是被加密的。PyArmor 是分两层加密的，第一层是模块中的每一个函数，第二层是整个模块。

**Comment by lhmwzy** [comment]
了解，谢谢。

**Comment by ShokuninSan** [comment]
Got the same warning. What is the resolution on this?

`
INFO     PyArmor Trial Version 5.3.3

INFO     Source path is "/app/src/xxx"
INFO     Entry script is src/xxx/__init__.py
INFO     Use cached capsule /root/.pyarmor_capsule.zip
INFO     Recursive mode is on
INFO     Save obfuscated scripts to "src.obfuscated/xxx"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
...
Warning: code object xxx isn't wrapped
...
`

Many thanks in advance!

**Comment by jondy** [comment]
It means this function isn't been obfuscated, because it includes some special instructions.

For example, there is 2-bytes instruction `JMP 255', after the code object is obfuscated, it will be changed to `jmp 267`, and the final instructions will be
```
EXTEND 1
JMP 11
```
In this case, it's complex to obfuscate the code object with wrap mode. So the code object is left as it's, but all the other code objects still are obfuscated.

In later version, it will be obfuscated with non wrap mode. 

In current version add some unused code in this function so that the operand isn't the critical value may avoid this warning.

**Comment by ShokuninSan** [comment]
Thanks @jondy for clarification! 

Will a version with obfuscation in non-wrap mode be released in the near future?

**Comment by jondy** [comment]
Not yet. But it will be implemented before the end of this year.

**Comment by jondy** [comment]
This issue has been fixed in v5.5.0
Refer to https://github.com/dashingsoft/pyarmor/releases/tag/v5.5.0
Please read the **Upgrade Notes** carefully before upgrading.
