### ISSUE TITLE
Question about #490

### ISSUE THREAD

**Issue by ChronoBrake** [dashingsoft/pyarmor#692]
Hey Sir,
Same as #490 
We using pyarmor for our tools, but one client don't have any physical network cards, only virtual wifi adapters. With disabled license he get error when trying to run "Get mac address failed". It's weird when we disabled license option he still receive it. It's bug or how he can got it work?
Best Regards

**Comment by jondy** [comment]
If use default license, it should not check mac address.

Do a test like this, in the clean path, create one simple script with only one print statement, obfuscate it like this
```
pyarmor obfuscate foo.py
```
Then send the obfuscate scripts to your customer, try it works or not.

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
Hi,

I have the same issue "Get mac address failed" although i haven't tried disabling Mac Address binding.

I'll test it out and update this ticket too.

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
Good news: when disabling mac address binding, it works fine. However i built my whole licensing flow around mac address binding. Should i stop using mac address binding, and use another licensing method (e.g call home?) or should i wait for a fix?

I appreciate that pyarmor is being thorough in checking for the physical nic. Maybe a fallback mechanism would be to call uuid.getnode() ?

**Comment by jondy** [comment]
I need to explain something.

When obfuscated scripts are bind to mac address

Case 1:

run it in a machine with virt nic only
obfuscated scripts failed because pyarmor could not get mac address

In this case I think It's OK for pyarmor.

Case 2:

run it in a machine with both virt nic and physic nic, and physic nic is exactly bind to license
obfuscated scripts is still failed because it could not get physic nic address

Only in this case, It's a bug of pyarmor.

So what's your case?
