### ISSUE TITLE
[Question] Distributing for other OS

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#821]
Hi Jondy and Mantainers

Recently I switched my main OS to macOS and I distribute it for users that uses windows.
When I run on macOS terminal the command

`pyarmor obfuscate main.py --no-runtime --platform windows.x86 --recursive --restrict 2 --advanced 4 `

It shows:
`VM Protect mode only works for Windows`

I was searching for something like that in Issues and documentation, there's not a thing about that, is there anyway to obfuscate with super mode (VM) for windows using macOS?

Thanks

**Comment by jondy** [comment]
It should not be problem. Now I'm in holiday, I'll check it when I'm back to office about Sep. 1.

**Comment by jondy** [comment]
I have checked the source, it need more work to support cross-platform `VM` mode. Because vm mode uses special key which only provided by windows. In a short, it need to build new `_pytransform.dylib` of Darwin to generate vm mode scripts.

At this time I have no plan to build this library only for  cross platform vm mode.
