### ISSUE TITLE
"Invalid input packet" when running obfuscating code

### ISSUE THREAD

**Issue by blechatellier** [dashingsoft/pyarmor#95]
Hi, I've obfuscated some code from a CI box and removed the default license.lic that was generated. When creating a custom license and running the obfuscated code I get:

```
Invalid input packet.
Check license failed
```

I made sure to run `pyarmor register` with my `CODE` before obfuscating the code and generating the license.

What would be the issue here? Do I need to generate the licenses using the same capsule as the one I obfuscated the code with?

**Comment by jondy** [comment]
Yes, the capsule must be same for obfuscating scripts and generating licenses.

If the default `license.lic` works, it's possible that the capsule used to generate license is different.

The output in the console will print which capsule is used, to be sure they're same.

Besides, if the scripts are obfuscated by project, note that maybe it still used the old capsule. Because the project capsule will not be upgraded after running `pyarmor register`, only the global capsule are updated.

The easy way is to remove the old project, and create new project after your CODE takes effect.
